from __future__ import annotations

import torch
from tad_mctc import storch
from tad_mctc.exceptions import DeviceError
from tad_mctc.math import einsum

from dxtb import IndexHelper
from dxtb._src.param import Param, get_elem_param
from dxtb._src.typing import (
    DD,
    Slicers,
    Tensor,
    TensorLike,
    TensorOrTensors,
    get_default_dtype,
    override,
)

from ..base import Interaction, InteractionCache
from ..coulomb.average import AveragingFunction, averaging_function, harmonic_average

__all__ = ["GCEMPBC", "LABEL_GCEMPBC", "new_gcempbc"]


LABEL_GCEMPBC = "GCEMPBC"

class GCEMPBCCache(InteractionCache, TensorLike):

    __store: Store | None
    """Storage for cache (required for culling)."""

    pot: Tensor
    """ MM Coulomb potential."""

    mat: Tensor
    """ QM Coulomb matrix."""

    __slots__ = ["__store", "pot"]

    def __init__(
        self, 
        pot: Tensor,
        mat: Tensor,
        device : torch.device | None = None,
        dtype : torch.dtype | None = None,
    ) -> None:
        super().__init__(
            device=device if device is None else pot.device,
            dtype=dtype if dtype is None else pot.dtype,
        )
        self.pot = pot
        self.mat = mat
        self.__store = None

    class Store:
        """
        Storage container for cache containing ``__slots__`` before culling.
        """

        pot: Tensor
        """Coulomb potential generated by MM"""

        mat: Tensor
        """Coulomb matrix between QM PBC images"""

        def __init__(self, pot: Tensor, mat: Tensor) -> None:
            self.pot = pot
            self.mat = mat

    def cull(self, conv: Tensor, slicers: Slicers) -> None:
        if self.__store is None:
            self.__store = self.Store(self.pot)

        raise RuntimeError("Not tested")
        slicer = slicers["shell"]
        self.pot = self.pot[[~conv, *slicer]]
        self.mat = self.mat[[~conv, *slicer, *slicer]]

    def restore(self) -> None:
        if self.__store is None:
            raise RuntimeError("Nothing to restore. Store is empty.")

        self.pot = self.__store.pot
        self.mat = self.__store.mat

class GCEMPBC(Interaction):

    hubbard: Tensor
    """ for QM atoms """

    lhubbard: Tensor
    """ for QM atoms """

    average: AveragingFunction
    """
    Function to use for averaging the Hubbard parameters (default:
    :func:`dxtb.components.interactions.coulomb.average.harmonic_average`).
    """

    mm_charges: Tensor

    mm_coords: Tensor

    mm_hubbard: Tensor

    box: Tensor
    """ Lattice vectors """

    rcut_ewald: torch.double
    """ Ewald real-space cutoff """

    eta: Tensor
    """ Ewald real-space exponent """

    mesh: Tensor
    """ Ewald grid mesh """

    Ls: Tensor
    """ lattice vectors needed in Ewald real-space """

    __slots__ = [
        "hubbard",
        "lhubbard",
        "mm_charges",
        "mm_coords",
        "mm_hubbard",
        "box",
        "rcut_ewald",
        "average",
        "eta",
        "mesh",
        "Ls"
    ]

    def __init__(
        self, 
        hubbard: Tensor,
        lhubbard: Tensor,
        mm_charges: Tensor,
        mm_coords: Tensor,
        mm_hubbard: Tensor,
        box: Tensor,
        rcut_ewald: torch.double,
        average: AveragingFunction = harmonic_average,
        device = None,
        dtype = None,
        ):
        super().__init__(device, dtype)

        self.hubbard = hubbard.to(**self.dd)
        self.lhubbard = lhubbard if lhubbard is None else lhubbard.to(**self.dd)
        self.mm_charges = mm_charges.to(**self.dd)
        self.mm_coords = mm_coords.to(**self.dd)
        self.mm_hubbard = mm_hubbard.to(**self.dd)
        self.box = box.to(**self.dd)
        self.rcut_ewald = rcut_ewald
        self.setup_ewald_params()
        self.average = average

    @property
    def vol(self):
        return abs(torch.det(self.box))

    def get_Gv_weights(self, mesh):
        dd: DD = {"device": self.device, "dtype": self.dtype}
        # Default, the 3D uniform grids
        rx = torch.fft.fftfreq(mesh[0], 1./mesh[0], **dd)
        ry = torch.fft.fftfreq(mesh[1], 1./mesh[1], **dd)
        rz = torch.fft.fftfreq(mesh[2], 1./mesh[2], **dd)
        b = torch.inverse(self.box) * 2 * torch.pi

        Gvbase = (rx, ry, rz)

        Gv = torch.matmul(cartesian_prod(Gvbase), b)

        # 1/cell.vol == det(b)/(2pi)^3
        weights = abs(torch.det(b)) /(2*torch.pi)**3
        return Gv, weights

    def get_lattice_Ls(self, rcut):
        dd: DD = {"device": self.device, "dtype": self.dtype}
#        # 1. find the smallest radius that bounds unit cell
#        Ts = cartesian_prod([[0.,1], [0,1], [0,1]]).to(**dd)
#        Ls = torch.matmul(Ts, self.box)
#        rb = torch.max(torch.norm(Ls, dim=-1)) / 2
#
#        # 2. find the largest Ts I need to check
#        Lmax = rcut + rb
#        Tmax = torch.max(torch.ceil(Lmax / torch.norm(self.box, dim=-1)))
#        Ts2check = cartesian_prod([torch.arange(-Tmax,Tmax+1)]*3).to(**dd)

#        # 3. find the actual Ts that overlaps with the rcut sphere
#        res = list()
#        Ts = cartesian_prod([[-0.5,0.5], [-0.5,0.5], [-0.5,0.5]]).to(**dd)
#        for T in Ts2check:
#            tmp = torch.matmul(T + Ts, self.box)
#            if torch.min(torch.norm(tmp, dim=-1)) <= rcut:
#                res.append(torch.matmul(T, self.box))
#
#        if len(res) == 0:
#            return torch.zeros((1,3), **dd)
#        else:
#            return torch.stack(res)
#        if len(Ts2check) == 0:
#            return torch.zeros((1,3), **dd)
#        else:
#            return torch.matmul(Ts2check, self.box)
        Tmax = torch.ceil(0.5 * ((4.1888*rcut**3/self.vol)**(1/3)-1)) + 1
        if Tmax == 0:
            return torch.zeros((1,3), **dd)
        else:
            return torch.matmul(
                cartesian_prod([torch.arange(-Tmax,Tmax+1)]*3).to(**dd),
                self.box
            )

    def get_ewald_params(self, rcut, precision=1e-6):
        from scipy.special import lambertw as l
        def lambertw(x):
            if x.device != 'cpu':
                return l(x.cpu().detach().clone())
            else:
                return l(x.detach().clone())
        e = precision
        Q = torch.sum(self.mm_charges**2) + 1000.
#        eta = 1 / rcut * torch.sqrt(lambertw(1/e*torch.sqrt(Q/2/self.vol)).real)
        eta = 1 / rcut * torch.sqrt(
            1.5 * 
            lambertw(
                2/3 * (4/e*Q/rcut/self.vol)**(2/3) * rcut**2
                ).real
            )
        L = self.vol**(1/3)
        kmax = 1.73205081*eta/2/torch.pi * torch.sqrt(lambertw( 4*Q**(2/3)/3/torch.pi**(2/3)/L**2/eta**(2/3) / e**(4/3) ).real)
        mesh = torch.ceil(torch.diag(self.box) * kmax).to(torch.int) * 2 + 1
        return eta.to(self.device), mesh.to(self.device)

    def setup_ewald_params(self):
        """ determine real-space cells, exponents, mesh """
        self.eta, self.mesh = self.get_ewald_params(self.rcut_ewald, precision=1e-6)
        self.Ls = self.get_lattice_Ls(self.rcut_ewald)

    # pylint: disable=unused-argument
    @override
    def get_cache(
        self,
        *,
        numbers: Tensor | None = None,
        positions: Tensor | None = None,
        ihelp: IndexHelper | None = None,
    ) -> GCEMPBCCache:
        if positions is None:
            raise ValueError("Positions are required for GCEMPBC cache.")
        if ihelp is None:
            raise ValueError("IndexHelper is required for GCEMPBC cache creation.")

        cachvars = (numbers.detach().clone(),
                    positions.detach().clone(),
                    self.mm_charges.detach().clone(),
                    self.mm_coords.detach().clone(),
                    self.mm_hubbard.detach().clone(),
                    self.box.detach().clone(),
                    self.rcut_ewald)

        if self.cache_is_latest(cachvars) is True:
            if not isinstance(self.cache, GCEMPBCCache):
                raise TypeError(
                    f"Cache in {self.label} is not of type '{self.label}."
                    "Cache'. This can only happen if you manually manipulate "
                    "the cache."
                )
            return self.cache

        # if the cache is built, store the cachvar for validation
        self._cachevars = cachvars

        self.cache = GCEMPBCCache(
            *self.get_shell_coulomb(positions, ihelp)
        )

        return self.cache

    def get_shell_coulomb(
        self,
        positions: Tensor,
        ihelp: IndexHelper,
    ) -> Tensor:
        """
        Calculate the Coulomb matrix.

        Parameters
        ----------
        numbers : Tensor
            Atomic numbers for all QM atoms in the system (shape: ``(..., nat)``).
        positions : Tensor
            Cartesian coordinates of all QM atoms (shape: ``(..., nat, 3)``).
        ihelp : IndexHelper
            Index mapping for the basis set.

        Returns
        -------
        Tensor
            MM Coulomb potential.
        Tensor
            QM Coulomb matrix.
        """
        if self.lhubbard is None:
            raise ValueError("No 'lhubbard' parameters set.")

        dd: DD = {"device": positions.device, "dtype": positions.dtype}
        eps = torch.tensor(torch.finfo(positions.dtype).eps, **dd)

        lh = ihelp.spread_ushell_to_shell(self.lhubbard)
        h = lh * ihelp.spread_uspecies_to_shell(self.hubbard)

        mm_coords = self.Ls[None] + self.mm_coords[:,None,:] # iLx
        dist12 = torch.norm(
            positions[:,None,None,:] - mm_coords[None],
            dim=-1) + eps # ijL

        qm_coords = self.Ls[None] + positions[:,None] # jLx
        #dist11 = torch.norm(
        #    positions[:,None,None,:] - qm_coords[None],
        #    dim=-1) + eps # ijL
        # compute dist11 as storch.cdist to avoid NaN when autograd
        norm1 = einsum('ix,ix->i', positions, positions)
        norm2 = einsum('jLx,jLx->jL', qm_coords, qm_coords)
        n = norm1[:,None,None] + norm2[None]
        prod = einsum('ix,jLx->ijL', positions, qm_coords)
        dist11 = storch.elemental.sqrt(n - 2.0 * prod, eps=eps)
        dist = storch.cdist(positions, positions, p=2) + eps

        dist12_shell = ihelp.spread_atom_to_shell(
            dist12, dim=-3, extra=True)
        dist11_shell_0 = ihelp.spread_atom_to_shell(
            dist11, dim=-3, extra=True)
        dist11_shell = ihelp.spread_atom_to_shell(
            dist11_shell_0, dim=-2, extra=True
        )
        dist_shell = ihelp.spread_atom_to_shell(dist, (-2,-1))

        # averaging function for hardnesses (Hubbard parameter)
        avg12 = self.average(h + eps, self.mm_hubbard + eps)
        avg11 = self.average(h + eps)

        # Ewald real-space
        ## QM - MM
        erfR12 = torch.special.erf(einsum("ijL,ij->ijL", dist12_shell, avg12))
        erfRewald12 = torch.special.erf(dist12_shell * self.eta)
        mat12 = (erfR12 - erfRewald12) / dist12_shell
        mat12 = torch.sum(mat12, dim=-1) # sum over cells
        pot_rs = einsum("ij,j->i", mat12, self.mm_charges)
        ## QM - QM images
        erfR11 = torch.special.erf(einsum("ijL,ij->ijL", dist11_shell, avg11))
        erfRewald11 = torch.special.erf(dist11_shell * self.eta)
        mat_rs = (erfR11 - erfRewald11) / dist11_shell
        mat_rs = torch.sum(mat_rs, dim=-1) # sum over cells
        ## unit cell QM - QM to be subtracted off (including Ewald self)
        mat_us = torch.special.erf(dist_shell * avg11) / dist_shell

        # Ewald k-space
        Gv, weights = self.get_Gv_weights(self.mesh)
        absG2 = einsum('gx,gx->g', Gv, Gv)
        absG2 = torch.where(absG2>0.0, absG2, 1e100)
        coulG = 4*torch.pi / absG2 * weights
        Gpref = torch.exp(-absG2/(4*self.eta**2)) * coulG
        GvRmm = einsum('gx,ix->ig', Gv, self.mm_coords)
        cosGvRmm = torch.cos(GvRmm)
        sinGvRmm = torch.sin(GvRmm)
        zcosGvRmm = einsum("i,ig->g", self.mm_charges, cosGvRmm)
        zsinGvRmm = einsum("i,ig->g", self.mm_charges, sinGvRmm)
        GvRqm = einsum('gx,ix->ig', Gv, ihelp.spread_atom_to_shell(positions, dim=-2, extra=True))
        cosGvRqm = torch.cos(GvRqm)
        sinGvRqm = torch.sin(GvRqm)
        ## QM pc - MM Ewald gc
        pot_ks  = einsum('ig,g->i', cosGvRqm, zcosGvRmm * Gpref) + \
                    einsum('ig,g->i', sinGvRqm, zsinGvRmm * Gpref)
        ## QM pc - QM Ewald gc
        mat_ks  = einsum('ig,jg,g->ij', cosGvRqm, cosGvRqm, Gpref) + \
                  einsum('ig,jg,g->ij', sinGvRqm, sinGvRqm, Gpref)

        return pot_rs + pot_ks, \
               2 * (mat_rs + mat_ks - mat_us)

    @override
    def get_shell_energy(self, charges: Tensor, cache: GCEMPBCCache) -> Tensor:
        return charges * cache.pot + 0.5 * einsum('i,ij,j->i', charges, cache.mat, charges)

    @override
    def get_shell_potential(self, charges: Tensor, cache: GCEMPBCCache) -> Tensor:
        return cache.pot + einsum('ij,j->', cache.mat, charges)

def cartesian_prod(arrays):
    arrays = [torch.as_tensor(x) for x in arrays]
    nd = len(arrays)
    dims = [nd] + [len(x) for x in arrays]
    out = torch.zeros(dims, dtype=arrays[0].dtype, device=arrays[0].device)
    shape = [-1] + [1] * nd
    for i, arr in enumerate(arrays):
        out[i] = arr.reshape(shape[:nd-i])
    return out.clone().reshape(nd,-1).T

def new_gcempbc(
        numbers: Tensor,
        par: Param,
        mm_charges: Tensor,
        mm_coords: Tensor,
        mm_hubbard: Tensor,
        box: Tensor,
        rcut_ewald: torch.double,
        average: AveragingFunction | None = None,
        device: torch.device | None = None,
        dtype: torch.dtype | None = None
) -> GCEMPBC | None:
    """
    Create new instance of :class:`.GCEMPBC`.

    Parameters
    ----------
    numbers : Tensor
        Atomic numbers for all atoms in the system (shape: ``(..., nat)``).
    par : Param
        Representation of an extended tight-binding model.
    mm_charges: Tensor
        Atom-resolved MM charges
    mm_coords: Tensor
        Cartesian coordinates of all MM charges
    mm_hubbard: Tensor
        Hubbard parameters of each MM charge
    box: Tensor
        Lattice vectors of unit cell
    rcut_ewald: torch.double
        Real-space cutoff for ewald

    Returns
    -------
    GCEMPBC | None
        Instance of the GCEMPBC class or ``None`` if no GCEMPBC is used.
    """
    if hasattr(par, "charge") is False or par.charge is None:
        return None

    if device is not None:
        if device != numbers.device:
            raise DeviceError(
                f"Passed device ({device}) and device of electric field "
                f"({numbers.device}) do not match."
            )

    dd: DD = {
        "device": device,
        "dtype": dtype if dtype is not None else get_default_dtype(),
    }

    unique = torch.unique(numbers)
    hubbard = get_elem_param(unique, par.element, "gam", **dd)
    lhubbard = get_elem_param(unique, par.element, "lgam", **dd)
    if average is None:
        average = averaging_function[par.charge.effective.average]

    return GCEMPBC(
        hubbard, lhubbard,
        mm_charges, mm_coords, mm_hubbard,
        box, rcut_ewald,
        average, **dd)