from __future__ import annotations

import torch
from tad_mctc import storch
from tad_mctc.exceptions import DeviceError
from tad_mctc.math import einsum

from dxtb import IndexHelper
from dxtb._src.param import Param, get_elem_param
from dxtb._src.typing import (
    DD,
    Slicers,
    Tensor,
    TensorLike,
    TensorOrTensors,
    get_default_dtype,
    override,
)

from ..base import Interaction, InteractionCache
from ..coulomb.average import AveragingFunction, averaging_function, harmonic_average

__all__ = ["GCEMPBC", "LABEL_GCEMPBC", "new_gcempbc"]


LABEL_GCEMPBC = "GCEMPBC"

class GCEMPBCCache(InteractionCache, TensorLike):

    __store: Store | None
    """Storage for cache (required for culling)."""

    pot: Tensor
    """ MM Coulomb potential."""

    mat: Tensor
    """ QM Coulomb matrix."""

    __slots__ = ["__store", "pot"]

    def __init__(
        self, 
        pot: Tensor,
        dippot: Tensor,
        mat: Tensor,
        device : torch.device | None = None,
        dtype : torch.dtype | None = None,
    ) -> None:
        super().__init__(
            device=device if device is None else pot.device,
            dtype=dtype if dtype is None else pot.dtype,
        )
        self.pot = pot
        self.dippot = dippot
        self.mat = mat
        self.__store = None

    class Store:
        """
        Storage container for cache containing ``__slots__`` before culling.
        """

        pot: Tensor
        """Coulomb potential generated by MM"""

        dippot: Tensor
        """ Coulomb potential grad generated by MM"""

        mat: Tensor
        """Coulomb matrix between QM PBC images"""

        def __init__(self, pot: Tensor, dippot: Tensor, mat: Tensor) -> None:
            self.pot = pot
            self.dippot = dippot
            self.mat = mat

    def cull(self, conv: Tensor, slicers: Slicers) -> None:
        raise NotImplementedError

    def restore(self) -> None:
        if self.__store is None:
            raise RuntimeError("Nothing to restore. Store is empty.")

        self.pot = self.__store.pot
        self.dippot = self.__store.dippot
        self.mat = self.__store.mat

class GCEMPBC(Interaction):

    hubbard: Tensor
    """ for QM atom shell-resolved charges """

    lhubbard: Tensor
    """ for QM atoms shell-resolved charges """

    diphubbard: Tensor
    """ for QM atom dipoles """

    average: AveragingFunction
    """
    Function to use for averaging the Hubbard parameters (default:
    :func:`dxtb.components.interactions.coulomb.average.harmonic_average`).
    """

    mm_charges: Tensor

    mm_coords: Tensor

    mm_hubbard: Tensor

    box: Tensor
    """ Lattice vectors """

    rcut_ewald: torch.double
    """ Ewald real-space cutoff """

    eta: Tensor
    """ Ewald real-space exponent """

    mesh: Tensor
    """ Ewald grid mesh """

    Ls: Tensor
    """ lattice vectors needed in Ewald real-space """

    independent_params: bool

    __slots__ = [
        "hubbard",
        "lhubbard",
        "diphubbard",
        "mm_charges",
        "mm_coords",
        "mm_hubbard",
        "box",
        "rcut_ewald",
        "average",
        "eta",
        "mesh",
        "Ls",
        "independent_params"
    ]

    def __init__(
        self, 
        hubbard: Tensor,
        lhubbard: Tensor,
        diphubbard: Tensor,
        mm_charges: Tensor,
        mm_coords: Tensor,
        mm_hubbard: Tensor,
        box: Tensor,
        rcut_ewald: torch.double,
        average: AveragingFunction = harmonic_average,
        device = None,
        dtype = None,
        independent_params: bool = False,
        ):
        super().__init__(device, dtype)

        self.hubbard = hubbard.to(**self.dd)
        self.lhubbard = lhubbard if lhubbard is None else lhubbard.to(**self.dd)
        self.diphubbard = diphubbard.to(**self.dd)
        self.mm_charges = mm_charges.to(**self.dd)
        self.mm_coords = mm_coords.to(**self.dd)
        self.mm_hubbard = mm_hubbard.to(**self.dd)
        self.box = box.to(**self.dd)
        self.rcut_ewald = rcut_ewald
        self.setup_ewald_params()
        self.average = average
        self.independent_params = independent_params

    @property
    def vol(self):
        return abs(torch.det(self.box))

    def get_Gv_weights(self, mesh):
        dd: DD = {"device": self.device, "dtype": self.dtype}
        # Default, the 3D uniform grids
        rx = torch.fft.fftfreq(mesh[0], 1./mesh[0], **dd)
        ry = torch.fft.fftfreq(mesh[1], 1./mesh[1], **dd)
        rz = torch.fft.fftfreq(mesh[2], 1./mesh[2], **dd)
        b = torch.inverse(self.box) * 2 * torch.pi

        Gvbase = (rx, ry, rz)

        Gv = torch.matmul(cartesian_prod(Gvbase), b)

        # 1/cell.vol == det(b)/(2pi)^3
        weights = abs(torch.det(b)) /(2*torch.pi)**3
        return Gv, weights

    def get_lattice_Ls(self, rcut):
        dd: DD = {"device": self.device, "dtype": self.dtype}
        Tmax = torch.ceil(0.5 * ((4.1888*rcut**3/self.vol)**(1/3)-1)) + 1
        if Tmax == 0:
            return torch.zeros((1,3), **dd)
        else:
            return torch.matmul(
                cartesian_prod([torch.arange(-Tmax,Tmax+1)]*3).to(**dd),
                self.box
            )

    def get_ewald_params(self, rcut, precision=1e-6):
        from scipy.special import lambertw as l
        def lambertw(x):
            if x.device != 'cpu':
                return l(x.cpu().detach().clone())
            else:
                return l(x.detach().clone())
        e = precision
        Q = torch.sum(self.mm_charges**2) + 1000.
#        eta = 1 / rcut * torch.sqrt(lambertw(1/e*torch.sqrt(Q/2/self.vol)).real)
        eta = 1 / rcut * torch.sqrt(
            1.5 * 
            lambertw(
                2/3 * (4/e*Q/rcut/self.vol)**(2/3) * rcut**2
                ).real
            )
        L = self.vol**(1/3)
        kmax = 1.73205081*eta/2/torch.pi * torch.sqrt(lambertw( 4*Q**(2/3)/3/torch.pi**(2/3)/L**2/eta**(2/3) / e**(4/3) ).real)
        mesh = torch.ceil(torch.diag(self.box) * kmax).to(torch.int) * 2 + 1
        return eta.to(self.device), mesh.to(self.device)

    def setup_ewald_params(self):
        """ determine real-space cells, exponents, mesh """
        self.eta, self.mesh = self.get_ewald_params(self.rcut_ewald, precision=1e-6)
        self.Ls = self.get_lattice_Ls(self.rcut_ewald)

    # pylint: disable=unused-argument
    @override
    def get_cache(
        self,
        *,
        numbers: Tensor | None = None,
        positions: Tensor | None = None,
        ihelp: IndexHelper | None = None,
    ) -> GCEMPBCCache:
        if positions is None:
            raise ValueError("Positions are required for GCEMPBC cache.")
        if ihelp is None:
            raise ValueError("IndexHelper is required for GCEMPBC cache creation.")

        cachvars = (numbers.detach().clone(),
                    positions.detach().clone(),
                    self.mm_charges.detach().clone(),
                    self.mm_coords.detach().clone(),
                    self.mm_hubbard.detach().clone(),
                    self.box.detach().clone(),
                    self.rcut_ewald)

        if self.cache_is_latest(cachvars) is True:
            if not isinstance(self.cache, GCEMPBCCache):
                raise TypeError(
                    f"Cache in {self.label} is not of type '{self.label}."
                    "Cache'. This can only happen if you manually manipulate "
                    "the cache."
                )
            return self.cache

        # if the cache is built, store the cachvar for validation
        self._cachevars = cachvars

        self.cache = GCEMPBCCache(
            *self.get_interaction_tensors(positions, ihelp)
        )

        return self.cache

    def get_interaction_tensors(
        self,
        positions: Tensor,
        ihelp: IndexHelper,
    ) -> Tensor:
        """
        Calculate the Coulomb matrix.

        Parameters
        ----------
        numbers : Tensor
            Atomic numbers for all QM atoms in the system (shape: ``(..., nat)``).
        positions : Tensor
            Cartesian coordinates of all QM atoms (shape: ``(..., nat, 3)``).
        ihelp : IndexHelper
            Index mapping for the basis set.

        Returns
        -------
        Tensor
            MM Coulomb potential.
        Tensor
            MM potential gradient.
        Tensor
            QM Coulomb matrix.
        """
        if self.lhubbard is None:
            raise ValueError("No 'lhubbard' parameters set.")

        dd: DD = {"device": positions.device, "dtype": positions.dtype}
        eps = torch.tensor(torch.finfo(positions.dtype).eps, **dd)

        if self.independent_params:
            h = self.hubbard * self.lhubbard
            dh = self.diphubbard
        else:
            lh = ihelp.spread_ushell_to_shell(self.lhubbard)
            h = lh * ihelp.spread_uspecies_to_shell(self.hubbard)
            dh = ihelp.spread_uspecies_to_atom(self.diphubbard)

        mm_coords = self.Ls[None] + self.mm_coords[:,None,:] # iLx
        R12 = positions[:,None,None,:] - mm_coords[None] # ijLx
        dist12 = torch.norm(R12, dim=-1) + eps # ijL

        qm_coords = self.Ls[None] + positions[:,None] # jLx
        #dist11 = torch.norm(
        #    positions[:,None,None,:] - qm_coords[None],
        #    dim=-1) + eps # ijL
        # compute dist11 as storch.cdist to avoid NaN when autograd
        norm1 = einsum('ix,ix->i', positions, positions)
        norm2 = einsum('jLx,jLx->jL', qm_coords, qm_coords)
        n = norm1[:,None,None] + norm2[None]
        prod = einsum('ix,jLx->ijL', positions, qm_coords)
        dist11 = storch.elemental.sqrt(n - 2.0 * prod, eps=eps)
        dist = storch.cdist(positions, positions, p=2) + eps

        dist12_shell = ihelp.spread_atom_to_shell(
            dist12, dim=-3, extra=True)
        dist11_shell_0 = ihelp.spread_atom_to_shell(
            dist11, dim=-3, extra=True)
        dist11_shell = ihelp.spread_atom_to_shell(
            dist11_shell_0, dim=-2, extra=True
        )
        dist_shell = ihelp.spread_atom_to_shell(dist, (-2,-1))

        # averaging function for hardnesses (Hubbard parameter)
        avg12 = self.average(h + eps, self.mm_hubbard + eps)
        avg11 = self.average(h + eps)
        avg12d = self.average(dh + eps, self.mm_hubbard + eps)

        # Ewald real-space
#        ## QM pc - MM
#        erfR12 = torch.special.erf(einsum("ijL,ij->ijL", dist12_shell, avg12))
#        erfRewald12 = torch.special.erf(dist12_shell * self.eta)
#        mat12 = (erfR12 - erfRewald12) / dist12_shell
#        mat12 = torch.sum(mat12, dim=-1) # sum over cells
#        pot_rs = einsum("ij,j->i", mat12, self.mm_charges)
#        # QM dip - MM
#        # TODO reduce duplicated work done here
#        ## QM dip - MM gc
#        ekR12 = torch.exp(-einsum("ijL,ij->ijL", dist12**2, avg12d**2))
#        Tij = torch.special.erf(einsum("ijL,ij->ijL", dist12, avg12d)) / dist12
#        invr3  = ( -Tij + 1.1283791670955126 * einsum("ijL,ij->ijL", ekR12, avg12d) ) / dist12**2  # 1.1283791670955126 = 2/sqrt(pi)
#        ## QM dip - MM ewald gc
#        ekR12 = torch.exp(-dist12**2 * self.eta**2)
#        Tij = torch.special.erf(dist12 * self.eta) / dist12
#        invr3 -= ( -Tij + 1.1283791670955126 * ekR12 * self.eta ) / dist12**2
#        dippot_rs = einsum("ijLx,ijL,j->ix", R12, invr3, self.mm_charges)
        ## (QM pc - MM gc) - (QM pc - MM ewald gc)
        mat12 = torch.special.erf(einsum("ijL,ij->ijL", dist12_shell, avg12)) / dist12_shell
        pot_rs = einsum("ijL,j->i", mat12, self.mm_charges)
        ## (QM dip - MM gc)  - (QM dip - MM ewald gc)
        Tij = torch.special.erf(dist12 * self.eta) / dist12
        tmp = einsum("ijLx,ijL->ijx", R12,
                (-torch.special.erf(einsum("ijL,ij->ijL", dist12, avg12d)) / dist12 + \
                  1.1283791670955126 * einsum("ijL,ij->ijL", torch.exp(-einsum("ijL,ij->ijL", dist12**2, avg12d**2)), avg12d) + \
                  Tij - 1.1283791670955126 * torch.exp(-dist12**2 * self.eta**2) * self.eta ) / dist12**2,
        )
        dippot_rs = einsum("ijx,j->ix", tmp, self.mm_charges)
        pot_rs -= ihelp.spread_atom_to_shell(einsum("ijL,j->i", Tij, self.mm_charges))
        ## QM - QM images
        erfR11 = torch.special.erf(einsum("ijL,ij->ijL", dist11_shell, avg11))
        erfRewald11 = torch.special.erf(dist11_shell * self.eta)
        mat_rs = (erfR11 - erfRewald11) / dist11_shell
        mat_rs = torch.sum(mat_rs, dim=-1) # sum over cells
        ## unit cell QM - QM to be subtracted off (including Ewald self)
        mat_us = torch.special.erf(dist_shell * avg11) / dist_shell

        # Ewald k-space
        Gv, weights = self.get_Gv_weights(self.mesh)
        absG2 = einsum('gx,gx->g', Gv, Gv)
        absG2 = torch.where(absG2>0.0, absG2, 1e100)
        coulG = 4*torch.pi / absG2 * weights
        Gpref = torch.exp(-absG2/(4*self.eta**2)) * coulG
        GvRmm = einsum('gx,ix->ig', Gv, self.mm_coords)
        cosGvRmm = torch.cos(GvRmm)
        sinGvRmm = torch.sin(GvRmm)
        zcosGvRmm = einsum("i,ig->g", self.mm_charges, cosGvRmm)
        zsinGvRmm = einsum("i,ig->g", self.mm_charges, sinGvRmm)
        GvRqm = einsum('gx,ix->ig', Gv, positions)
        cosGvRqm = torch.cos(GvRqm)
        sinGvRqm = torch.sin(GvRqm)
        ## QM pc - MM Ewald gc
        pot_ks  = einsum('ig,g->i', cosGvRqm, zcosGvRmm * Gpref) + \
                    einsum('ig,g->i', sinGvRqm, zsinGvRmm * Gpref)
        pot_ks = ihelp.spread_atom_to_shell(pot_ks, dim=-1)
        ## QM pc - QM Ewald gc
        mat_ks  = einsum('ig,jg,g->ij', cosGvRqm, cosGvRqm, Gpref) + \
                  einsum('ig,jg,g->ij', sinGvRqm, sinGvRqm, Gpref)
        mat_ks = mat_ks.unsqueeze(2)
        mat_ks = ihelp.spread_atom_to_shell(mat_ks, dim=-3, extra=True)
        mat_ks = ihelp.spread_atom_to_shell(mat_ks, dim=-2, extra=True)
        mat_ks = mat_ks.squeeze()
        # QM dip - MM Ewald gc
        dippot_ks = -einsum('gx,ig,g->ix', Gv, sinGvRqm, zcosGvRmm * Gpref) + \
                    einsum('gx,ig,g->ix', Gv, cosGvRqm, zsinGvRmm * Gpref)

        return pot_rs + pot_ks, \
               dippot_rs + dippot_ks, \
               2 * (mat_rs + mat_ks - mat_us)

    @override
    def get_shell_energy(self, charges: Tensor, cache: GCEMPBCCache) -> Tensor:
        return charges * cache.pot + 0.5 * einsum('i,ij,j->i', charges, cache.mat, charges)

    @override
    def get_dipole_energy(self, charges: Tensor, cache: GCEMPBCCache) -> Tensor:
        return einsum('ix,ix->i', charges, cache.dippot)

    @override
    def get_shell_potential(self, charges: Tensor, cache: GCEMPBCCache) -> Tensor:
        return cache.pot + einsum('ij,j->', cache.mat, charges)

    @override
    def get_dipole_potential(self, _: Tensor, cache: GCEMPBCCache) -> Tensor:
        return cache.dippot
    
def cartesian_prod(arrays):
    arrays = [torch.as_tensor(x) for x in arrays]
    nd = len(arrays)
    dims = [nd] + [len(x) for x in arrays]
    out = torch.zeros(dims, dtype=arrays[0].dtype, device=arrays[0].device)
    shape = [-1] + [1] * nd
    for i, arr in enumerate(arrays):
        out[i] = arr.reshape(shape[:nd-i])
    return out.clone().reshape(nd,-1).T

def new_gcempbc(
        numbers: Tensor,
        par: Param | dict,
        mm_charges: Tensor,
        mm_coords: Tensor,
        mm_hubbard: Tensor,
        box: Tensor,
        rcut_ewald: torch.double,
        average: AveragingFunction | None = None,
        device: torch.device | None = None,
        dtype: torch.dtype | None = None,
        independent_params: bool = False,
) -> GCEMPBC | None:
    """
    Create new instance of :class:`.GCEMPBC`.

    Parameters
    ----------
    numbers : Tensor
        Atomic numbers for all atoms in the system (shape: ``(..., nat)``).
    par : Param
        Representation of an extended tight-binding model.
    mm_charges: Tensor
        Atom-resolved MM charges
    mm_coords: Tensor
        Cartesian coordinates of all MM charges
    mm_hubbard: Tensor
        Hubbard parameters of each MM charge
    box: Tensor
        Lattice vectors of unit cell
    rcut_ewald: torch.double
        Real-space cutoff for ewald

    Returns
    -------
    GCEMPBC | None
        Instance of the GCEMPBC class or ``None`` if no GCEMPBC is used.
    """
    if type(par) is dict:
        hubbard = par['hubbard']
        lhubbard = par['lhubbard']
        par = par['xtbpar']
        diphubbard = par.get('diphubbard', None)
    if hasattr(par, "charge") is False or par.charge is None:
        return None

    if device is not None:
        if device != numbers.device:
            raise DeviceError(
                f"Passed device ({device}) and device of electric field "
                f"({numbers.device}) do not match."
            )

    dd: DD = {
        "device": device,
        "dtype": dtype if dtype is not None else get_default_dtype(),
    }

    if independent_params:
        pass
    else:
        unique = torch.unique(numbers)
        hubbard = get_elem_param(unique, par.element, "gam", **dd)
        lhubbard = get_elem_param(unique, par.element, "lgam", **dd)
        diphubbard = get_elem_param(unique, par.element, "gam", **dd)
    if average is None:
        average = averaging_function[par.charge.effective.average]

    return GCEMPBC(
        hubbard, lhubbard, diphubbard,
        mm_charges, mm_coords, mm_hubbard,
        box, rcut_ewald,
        average,
        independent_params=independent_params,
        **dd)
