from __future__ import annotations

import torch
from tad_mctc import storch
from tad_mctc.exceptions import DeviceError
from tad_mctc.math import einsum

from dxtb import IndexHelper
from dxtb._src.param import Param, get_elem_param
from dxtb._src.typing import (
    DD,
    Slicers,
    Tensor,
    TensorLike,
    TensorOrTensors,
    get_default_dtype,
    override,
)

from ..base import Interaction, InteractionCache
from ..coulomb.average import AveragingFunction, averaging_function, harmonic_average

__all__ = ["PCEM", "LABEL_PCEM", "new_pcem"]


LABEL_PCEM = "PCEM"

class PCEMCache(InteractionCache, TensorLike):

    __store: Store | None
    """Storage for cache (required for culling)."""

    pot: Tensor
    """Coulomb potential."""

    __slots__ = ["__store", "pot"]

    def __init__(
        self, 
        pot: Tensor,
        device : torch.device | None = None,
        dtype : torch.dtype | None = None,
    ) -> None:
        super().__init__(
            device=device if device is None else pot.device,
            dtype=dtype if dtype is None else pot.dtype,
        )
        self.pot = pot
        self.__store = None

    class Store:
        """
        Storage container for cache containing ``__slots__`` before culling.
        """

        pot: Tensor
        """Coulomb potential generated by MM"""

        def __init__(self, pot: Tensor) -> None:
            self.pot = pot

    def cull(self, conv: Tensor, slicers: Slicers) -> None:
        if self.__store is None:
            self.__store = self.Store(self.pot)

        raise RuntimeError("Not tested")
        slicer = slicers["shell"]
        self.pot = self.pot[[~conv, *slicer]]

    def restore(self) -> None:
        if self.__store is None:
            raise RuntimeError("Nothing to restore. Store is empty.")

        self.pot = self.__store.pot

class PCEM(Interaction):

    hubbard: Tensor
    """ for QM atoms """

    lhubbard: Tensor
    """ for QM atoms """

    average: AveragingFunction
    """
    Function to use for averaging the Hubbard parameters (default:
    :func:`dxtb.components.interactions.coulomb.average.harmonic_average`).
    """

    mm_charges: Tensor

    mm_coords: Tensor

    mm_hubbard: Tensor

    __slots__ = [
        "hubbard",
        "lhubbard",
        "mm_charges",
        "mm_coords",
        "mm_hubbard",
        "average"
    ]

    def __init__(
        self, 
        hubbard: Tensor,
        lhubbard: Tensor,
        mm_charges: Tensor,
        mm_coords: Tensor,
        mm_hubbard: Tensor,
        average: AveragingFunction = harmonic_average,
        device = None,
        dtype = None,
        ):
        super().__init__(device, dtype)

        self.hubbard = hubbard.to(**self.dd)
        self.lhubbard = lhubbard if lhubbard is None else lhubbard.to(**self.dd)
        self.mm_charges = mm_charges.to(**self.dd)
        self.mm_coords = mm_coords.to(**self.dd)
        self.mm_hubbard = mm_hubbard.to(**self.dd)
        self.average = average

    # pylint: disable=unused-argument
    @override
    def get_cache(
        self,
        *,
        numbers: Tensor | None = None,
        positions: Tensor | None = None,
        ihelp: IndexHelper | None = None,
    ) -> PCEMCache:
        if positions is None:
            raise ValueError("Positions are required for PCEM cache.")
        if ihelp is None:
            raise ValueError("IndexHelper is required for PCEM cache creation.")

        cachvars = (numbers.detach().clone(),
                    positions.detach().clone(),
                    self.mm_charges.detach().clone(),
                    self.mm_coords.detach().clone(),
                    self.mm_hubbard.detach().clone())

        if self.cache_is_latest(cachvars) is True:
            if not isinstance(self.cache, PCEMCache):
                raise TypeError(
                    f"Cache in {self.label} is not of type '{self.label}."
                    "Cache'. This can only happen if you manually manipulate "
                    "the cache."
                )
            return self.cache

        # if the cache is built, store the cachvar for validation
        self._cachevars = cachvars

        self.cache = PCEMCache(
            self.get_shell_coulomb_potential(positions, ihelp)
        )

        return self.cache

    def get_shell_coulomb_potential(
        self,
        positions: Tensor,
        ihelp: IndexHelper,
    ) -> Tensor:
        mat = self.get_shell_coulomb_matrix(positions, ihelp)
        pot = einsum('...ik,k->i', mat, self.mm_charges)
        return pot

    def get_shell_coulomb_matrix(
        self,
        positions: Tensor,
        ihelp: IndexHelper,
    ) -> Tensor:
        """
        Calculate the Coulomb matrix.

        Parameters
        ----------
        numbers : Tensor
            Atomic numbers for all QM atoms in the system (shape: ``(..., nat)``).
        positions : Tensor
            Cartesian coordinates of all QM atoms (shape: ``(..., nat, 3)``).
        ihelp : IndexHelper
            Index mapping for the basis set.
        mm_charges: Tensor
            Atom-resolved MM charges
        mm_coords: Tensor
            Cartesian coordinates of all MM charges
        mm_hubbard: Tensor
        Hubbard parameters of each MM charge

        Returns
        -------
        Tensor
            Coulomb matrix.
        """
        if self.lhubbard is None:
            raise ValueError("No 'lhubbard' parameters set.")

        mat = coulomb_matrix_shell(
            positions,
            ihelp,
            self.hubbard,
            self.lhubbard,
            self.mm_coords,
            self.mm_hubbard,
            self.average,
        )
        assert mat is not None

        return mat

    @override
    def get_shell_energy(self, charges: Tensor, cache: PCEMCache) -> Tensor:
        pot = self.get_shell_potential(charges, cache)
        return charges * pot

    @override
    def get_shell_potential(self, _: Tensor, cache: PCEMCache) -> Tensor:
        return cache.pot + 0.0

def coulomb_matrix_shell(
    positions: Tensor,
    ihelp: IndexHelper,
    hubbard: Tensor,
    lhubbard: Tensor,
    mm_coords: Tensor,
    mm_hubbard: Tensor,
    average: AveragingFunction,
) -> Tensor:
    """
    Calculate the shell-resolved Coulomb matrix.

    Parameters
    ----------
    positions : Tensor
        Cartesian coordinates of all atoms (shape: ``(..., nat, 3)``).
    ihelp : IndexHelper
        Index mapping for the basis set.
    hubbard : Tensor
        Hubbard parameters of all elements.
    lhubbard: Tensor
        Shell-resolved scaling factors for Hubbard parameters (default:
        ``None``, i.e., no shell resolution).
    mm_charges: Tensor
        Atom-resolved MM charges
    mm_coords: Tensor
        Cartesian coordinates of all MM charges
    mm_hubbard: Tensor
        Hubbard parameters of each MM charge
    average: AveragingFunction
        Function to use for averaging the Hubbard parameters (default:
        :func:`dxtb.components.interactions.coulomb.average.harmonic_average`).

    Returns
    -------
    Tensor
        Coulomb matrix.
    """
    dd: DD = {"device": positions.device, "dtype": positions.dtype}
    eps = torch.tensor(torch.finfo(positions.dtype).eps, **dd)

    gexp = 2.0

    lh = ihelp.spread_ushell_to_shell(lhubbard)
    h = lh * ihelp.spread_uspecies_to_shell(hubbard)

    dist = storch.cdist(positions, mm_coords, p=2)

    # all distances to the power of "gexp" (R^2_AB from Eq.26)
    dist_gexp = ihelp.spread_atom_to_shell(
        torch.pow(dist + eps, gexp),
        dim=-2,
        extra=True
    )

    # Eq.30: averaging function for hardnesses (Hubbard parameter)
    avg = average(h + eps, mm_hubbard + eps)

    # Eq.26: Coulomb matrix
    tmp = dist_gexp + torch.pow(avg, -gexp)
    return 1.0 / torch.pow(tmp, 1.0 / gexp)

def new_pcem(
        numbers: Tensor,
        par: Param,
        mm_charges: Tensor,
        mm_coords: Tensor,
        mm_hubbard: Tensor,
        average: AveragingFunction | None = None,
        device: torch.device | None = None,
        dtype: torch.dtype | None = None
) -> PCEM | None:
    """
    Create new instance of :class:`.PCEM`.

    Parameters
    ----------
    numbers : Tensor
        Atomic numbers for all atoms in the system (shape: ``(..., nat)``).
    par : Param
        Representation of an extended tight-binding model.
    mm_charges: Tensor
        Atom-resolved MM charges
    mm_coords: Tensor
        Cartesian coordinates of all MM charges
    mm_hubbard: Tensor
        Hubbard parameters of each MM charge

    Returns
    -------
    PCEM | None
        Instance of the PCEM class or ``None`` if no PCEM is used.
    """
    if hasattr(par, "charge") is False or par.charge is None:
        return None

    if device is not None:
        if device != numbers.device:
            raise DeviceError(
                f"Passed device ({device}) and device of electric field "
                f"({numbers.device}) do not match."
            )

    dd: DD = {
        "device": device,
        "dtype": dtype if dtype is not None else get_default_dtype(),
    }

    unique = torch.unique(numbers)
    hubbard = get_elem_param(unique, par.element, "gam", **dd)
    lhubbard = get_elem_param(unique, par.element, "lgam", **dd)
    if average is None:
        average = averaging_function[par.charge.effective.average]

    return PCEM(
        hubbard, lhubbard,
        mm_charges, mm_coords, mm_hubbard,
        average, **dd)